CLUSTAL format alignment by MAFFT L-INS-i (v7.455)

																   #TM1 
Q8NGI8|O5AN1    M---------------------------TGGGNITEITYFILLGFSDFPR-IIKVLFTIF
Q8NGW6|OR6K6    MKQYSVGNQHSNYRSLLFPFLCSQMTQLTASGNQTMVTEFLFSMFPHAHR-GGLLFFIPL
Q8NGV6|OR5H6    MFL---------YLCFIFQRTCSE---EMEEENATLLTEFVLTGFLHQPD-CKIPLFLAF
A6NND4|O2AT4    MDA----------------TACNE---SVDGSPV-----FYLLGIPSLPETFFLPVFFIF
                *                                      * :  :          .*  :
								 TM1#      #TM2                    TM2#
Q8NGI8|O5AN1    LVIYITSLAWNLSLIVLIRMDSHLHTPMYFFLSNLSFIDVCYISSTVPKMLSNLLQEQQT
Q8NGW6|OR6K6    LLIYGFILTGNLIMFIVIQVGMALHTPLYFFISVLSFLEICYTTTTIPKMLSCLISEQKS
Q8NGV6|OR5H6    LVIYLITIMGNLGLIVLIWKDPHLHIPMYLFLGSLAFVDASLSSTVTPKMLINFLAKSKM
A6NND4|O2AT4    LLFYLLILMGNALILVAVVAEPSLHKPMYFFLINLSTLDILFTTTTVPKMLSLFLLGDRF
                *::*   :  *  ::: :     ** *:*:*:  *: ::    ::. ****  ::  .: 
                 #TM3                              TM3#       #TM4
Q8NGI8|O5AN1    ITFVGCIIQYFIFSTMGLSESCLMTAMAYDRYAAICNPLLYSSIMSPTLCVWMVLGAYMT
Q8NGW6|OR6K6    ISVAGCLLQMYFFHSLGITESCVLTAMAIDRYIAICNPLRYPTIMIPKLCIQLTVGSCFC
Q8NGV6|OR5H6    ISLSECMVQFFSLVTTVTTECFLLATMAYDRYVAICKALLYPVIMTNELCIQLLVLSFIG
A6NND4|O2AT4    LSFSSCLLQMYLFQSFTCSEAFILVVMAYDRYVAICHPLHYPVLMNPQTNATLAASAWLT
                ::.  *::* : : :   :*. ::..** *** ***:.* *. :*       :   : : 
                        TM4##ECL2                      ECL2##TM5
Q8NGI8|O5AN1    GLTASLFQIGALLQLHFCGSNVIRHFFCDMPQLLILSCTDTFFVQVMTAILTMFFGIASA
Q8NGW6|OR6K6    GFLLVLPEIAWISTLPFCGSNQIHQIFCDFTPVLSLACTDTFLVVIVDAIHAAEI-VASF
Q8NGV6|OR5H6    GLLHALIHEAFSFRLTFCNSNIIQHFYCDIIPLLKISCTDSSINFLMVFIFAGSVQVFTI
A6NND4|O2AT4    ALLLPIPAVVRTSQMAYNSIAYIYHCFCDHLAVVQASCSDTTPQTLMGFCIAMVVSFLPL
                .:   :        : : .   * : :**   ::  :*:*:    ::    :  . . . 
                             TM5#     #TM6                     TM6#    #TM7   
Q8NGI8|O5AN1    LVIMISYGYIGISIMKITSAKGRSKAFNTCASHLTAVSLFYTSGIFVYLSSSSGGSSSFD
Q8NGW6|OR6K6    LVIALSYIRIIIVILGMHSAEGHHKAFSTCAAHLAVFLLFFGSVAVMYLRFSATYSVFWD
Q8NGV6|OR5H6    GTILISYTIILFTILEKKSIKGIRKAVSTCGAHLLSVSLYYGPLTFKYLGSASPQADDQD
A6NND4|O2AT4    LLVLLSYVHILASVLRISSLEGRAKAFSTCSSHLLVVGTYYSSIAIAYVAYRADLPLDFH
                  : :**  *   ::   * :*  **..**.:**  .  :: .  . *:   :  .   .
                                 TM7#
Q8NGI8|O5AN1    RFASVFYTVVIPMLNPLIYSLRNKEIKDALKRLQKRKC------C
Q8NGW6|OR6K6    TAIAVTFVILAPFFNPIIYSLKNKDMKEAIGRLFHYQKRAGWAGK
Q8NGV6|OR5H6    MMESLFYTVIVPLLNPMIYSLRNKQVIASFTKMFKSN-------V
A6NND4|O2AT4    IMGNVVYAILTPILNPLIYTLRNRDVKAAITKIMSQDPGCDRS-I
                    : :.:: *::**:**:*:*:::  :: ::   .        
